version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-universidad
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=oracle-universidad
      - DB_PORT=1521
      - DB_SERVICE=XEPDB1
      - DB_USER=app_user
      - DB_PASSWORD=AppPass1234
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - universidad-net

networks:
  universidad-net:
    external: true
