-- ============================================================
-- DML
-- ============================================================
-- Este script es COMPLETO y autonomo. No depende de datos semilla del DDL.
-- Incluye Seccion 0 con todos los datos base (antes en DDL Seccion 6).
-- Este DML agrega (ademas de los datos base):
--   Asignaturas adicionales (IDs 11-25) para completar 5 por semestre
--   Semestre 3 para los 3 programas con 5 asignaturas cada uno
--   5 estudiantes adicionales (para llegar a 10)
--   10 volantes de matricula (uno por estudiante)
--   CUENTA_CORRIENTE (creada automaticamente por trigger)
--   VOLANTE_MATRICULA_ASIGNATURA (para volantes CREDITOS)
--   Movimientos de cobro y pago variados
--   Transacciones de pago
-- ============================================================
-- SECCION 0: DATOS BASE (antes en DDL Seccion 6)
-- ============================================================

PROMPT >>> Insertando datos base...

-- 0.1 PERFIL
INSERT INTO PERFIL (ID_PERFIL, NOMBRE_PERFIL) VALUES (SEQ_PERFIL.NEXTVAL, 'ADMINISTRADOR');
INSERT INTO PERFIL (ID_PERFIL, NOMBRE_PERFIL) VALUES (SEQ_PERFIL.NEXTVAL, 'SUPERVISOR');
INSERT INTO PERFIL (ID_PERFIL, NOMBRE_PERFIL) VALUES (SEQ_PERFIL.NEXTVAL, 'ASISTENTE');

-- 0.2 MENU
-- IDs asignados por secuencia. Orden = ID_MENU esperado:
--  1  Gestion de Usuarios        => perm VER_USUARIOS / CREAR_USUARIO / EDITAR_USUARIO / ELIMINAR_USUARIO
--  2  Gestion de Perfiles        => perm GESTIONAR_PERFILES
--  3  Gestion de Menus           => perm GESTIONAR_MENUS
--  4  Gestion de Programas       => perm GESTIONAR_PROGRAMAS
--  5  Gestion de Asignaturas     => perm GESTIONAR_ASIGNATURAS
--  6  Periodos Academicos        => perm GESTIONAR_PROGRAMAS / GESTIONAR_REGLAS
--  7  Gestion de Estudiantes     => perm GESTIONAR_ESTUDIANTES
--  8  Reglas de Cobro            => perm GESTIONAR_REGLAS
--  9  Codigos de Detalle         => perm GESTIONAR_CODIGOS
-- 10  Generar Cobro Individual   => perm GENERAR_COBRO_IND
-- 11  Cobros Adicionales         => perm COBROS_ADICIONALES
-- 12  Cobro Masivo               => perm GENERAR_COBRO_MAS
-- 13  Registrar Pago             => perm REGISTRAR_PAGO
-- 14  Cuenta Corriente           => perm VER_CUENTA
-- 15  Consultar Pagos            => perm VER_REPORTES
-- 16  Reportes                   => perm VER_REPORTES
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Usuarios',       'pages/usuarios.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Perfiles',       'pages/perfiles.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Menus',          'pages/menus.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Programas',      'pages/programas.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Asignaturas',    'pages/asignaturas-catalogo.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Periodos Academicos',       'pages/periodos.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Gestion de Estudiantes',    'pages/estudiantes.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Reglas de Cobro',           'pages/reglas-cobro.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Codigos de Detalle',        'pages/codigos-detalle.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Generar Cobro Individual',  'pages/generar-cobro.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Cobros Adicionales',        'pages/cobros-adicionales.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Cobro Masivo',              'pages/cobro-masivo.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Registrar Pago',            'pages/registrar-pago.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Cuenta Corriente',          'pages/cuenta-corriente.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Consultar Pagos',           'pages/consultar-pagos.html');
INSERT INTO MENU (ID_MENU, NOMBRE_FUNCION, URL_ACCESO) VALUES (SEQ_MENU.NEXTVAL, 'Reportes',                  'pages/reportes.html');

-- 0.3 PERMISO
-- Un permiso por menu. Los permisos de usuarios (CRUD) apuntan al mismo menu.
-- ID_MENU ahora con 16 menus; permisos de usuario siguen en menu 1.
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'VER_USUARIOS',          'Ver y consultar lista de usuarios',              1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'CREAR_USUARIO',         'Crear nuevo usuario del sistema',                1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'EDITAR_USUARIO',        'Modificar datos de usuario',                     1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'ELIMINAR_USUARIO',      'Eliminar usuario del sistema',                   1);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_PERFILES',    'Crear/editar perfiles y asignar permisos',       2);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_MENUS',       'Crear/editar opciones de menu del sistema',      3);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_PROGRAMAS',   'Administrar programas academicos y planes',      4);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_ASIGNATURAS', 'Administrar asignaturas del catalogo',            5);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_PERIODOS',    'Gestionar periodos academicos',                  6);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_ESTUDIANTES', 'Registrar y editar datos de estudiantes',        7);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_REGLAS',      'Definir reglas de cobro por periodo/programa',   8);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_CODIGOS',     'Administrar codigos de detalle financieros',     9);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GENERAR_COBRO_IND',     'Generar volante de matricula individual',        10);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'COBROS_ADICIONALES',    'Agregar cargos individuales adicionales a la cuenta corriente', 11);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GENERAR_COBRO_MAS',     'Generar volantes de matricula en masa',          12);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'REGISTRAR_PAGO',        'Registrar pagos en cuenta corriente',            13);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'VER_CUENTA',            'Consultar cuenta corriente del estudiante',      14);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'CONSULTAR_PAGOS',       'Consultar historial de pagos y transacciones',   15);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'VER_REPORTES',          'Ver reportes financieros y consultar pagos realizados', 16);
INSERT INTO PERMISO (ID_PERMISO, NOMBRE_OPERACION, DESCRIPCION, ID_MENU) VALUES (SEQ_PERMISO.NEXTVAL, 'GESTIONAR_USUARIOS',    'Crear, editar y eliminar cuentas de usuario del sistema', 1);

-- 0.4 PERFIL_PERMISO
-- ADMINISTRADOR: todos los permisos
DECLARE v_id NUMBER;
BEGIN
    SELECT ID_PERFIL INTO v_id FROM PERFIL WHERE NOMBRE_PERFIL = 'ADMINISTRADOR';
    FOR p IN (SELECT ID_PERMISO FROM PERMISO) LOOP
        INSERT INTO PERFIL_PERMISO VALUES (v_id, p.ID_PERMISO);
    END LOOP;
END;
/
-- SUPERVISOR: gestion academica + periodos + reportes
DECLARE v_id NUMBER;
BEGIN
    SELECT ID_PERFIL INTO v_id FROM PERFIL WHERE NOMBRE_PERFIL = 'SUPERVISOR';
    FOR p IN (SELECT ID_PERMISO FROM PERMISO WHERE NOMBRE_OPERACION IN (
        'GESTIONAR_PROGRAMAS','GESTIONAR_ASIGNATURAS','GESTIONAR_PERIODOS',
        'GESTIONAR_ESTUDIANTES','GESTIONAR_REGLAS','GESTIONAR_CODIGOS','VER_REPORTES','CONSULTAR_PAGOS')) LOOP
        INSERT INTO PERFIL_PERMISO VALUES (v_id, p.ID_PERMISO);
    END LOOP;
END;
/
-- ASISTENTE: operaciones financieras diarias
DECLARE v_id NUMBER;
BEGIN
    SELECT ID_PERFIL INTO v_id FROM PERFIL WHERE NOMBRE_PERFIL = 'ASISTENTE';
    FOR p IN (SELECT ID_PERMISO FROM PERMISO WHERE NOMBRE_OPERACION IN (
        'GENERAR_COBRO_IND','COBROS_ADICIONALES','GENERAR_COBRO_MAS','REGISTRAR_PAGO','VER_CUENTA')) LOOP
        INSERT INTO PERFIL_PERMISO VALUES (v_id, p.ID_PERMISO);
    END LOOP;
END;
/

-- 0.5 CODIGO_DETALLE
INSERT INTO CODIGO_DETALLE VALUES ('PMAT', 'COBRO', 'Valor Global por programa',   NULL);
INSERT INTO CODIGO_DETALLE VALUES ('PCRE', 'COBRO', 'Valor crédito por programa',  NULL);
INSERT INTO CODIGO_DETALLE VALUES ('PCAR', 'COBRO', 'Carné digital',               85000);
INSERT INTO CODIGO_DETALLE VALUES ('PLAB', 'COBRO', 'Laboratorios Médicos',        350000);
INSERT INTO CODIGO_DETALLE VALUES ('PEXA', 'COBRO', 'Exámenes de ingreso',         120000);
INSERT INTO CODIGO_DETALLE VALUES ('MPAG', 'PAGO',  'Valor pagado para Matrícula', NULL);
INSERT INTO CODIGO_DETALLE VALUES ('ANT',  'PAGO',  'Anticipo',                    NULL);
INSERT INTO CODIGO_DETALLE VALUES ('DESC', 'PAGO',  'Descuento',                   NULL);
INSERT INTO CODIGO_DETALLE VALUES ('CRED', 'PAGO',  'Crédito financiero',          NULL);

-- 0.6 PROGRAMA_ACADEMICO
INSERT INTO PROGRAMA_ACADEMICO (ID_PROGRAMA, NOMBRE_PROGRAMA, CODIGO_PROGRAMA) VALUES (SEQ_PROGRAMA.NEXTVAL, 'Ingeniería de Sistemas',    'SIS');
INSERT INTO PROGRAMA_ACADEMICO (ID_PROGRAMA, NOMBRE_PROGRAMA, CODIGO_PROGRAMA) VALUES (SEQ_PROGRAMA.NEXTVAL, 'Administración de Empresas', 'ADM');
INSERT INTO PROGRAMA_ACADEMICO (ID_PROGRAMA, NOMBRE_PROGRAMA, CODIGO_PROGRAMA) VALUES (SEQ_PROGRAMA.NEXTVAL, 'Medicina',                   'MED');

-- 0.7 PERIODO_ACADEMICO
INSERT INTO PERIODO_ACADEMICO (ID_PERIODO, NOMBRE_PERIODO, FECHA_INICIO, FECHA_FIN)
    VALUES (SEQ_PERIODO.NEXTVAL, '2026-10', DATE '2026-01-15', DATE '2026-06-15');
INSERT INTO PERIODO_ACADEMICO (ID_PERIODO, NOMBRE_PERIODO, FECHA_INICIO, FECHA_FIN)
    VALUES (SEQ_PERIODO.NEXTVAL, '2026-20', DATE '2026-07-15', DATE '2026-11-30');

-- 0.8 ASIGNATURA
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Cálculo Diferencial',         3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Fundamentos de Programación', 3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Álgebra Lineal',              3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Bases de Datos I',            3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Física I',                    3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Contabilidad General',        3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Microeconomía',               3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Inglés I',                    2);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Anatomía Humana',             4);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS) VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Biología Celular',            4);

-- 0.9 PLAN_ESTUDIO
INSERT INTO PLAN_ESTUDIO VALUES (1, 1);
INSERT INTO PLAN_ESTUDIO VALUES (2, 1);
INSERT INTO PLAN_ESTUDIO VALUES (1, 2);
INSERT INTO PLAN_ESTUDIO VALUES (2, 2);
INSERT INTO PLAN_ESTUDIO VALUES (1, 3);
INSERT INTO PLAN_ESTUDIO VALUES (2, 3);

-- 0.10 PLAN_ESTUDIO_ASIGNATURA
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 1, 1);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 1, 2);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 1, 3);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 1, 5);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 1, 4);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 1, 8);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 2, 6);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 2, 7);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 2, 8);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 2, 1);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 2, 8);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 3, 9);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 3, 10);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 3, 5);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 3, 8);

-- 0.11 REGLA_COBRO
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      8500000,  1, 1);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 650000,    NULL,     1, 1);
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      6500000,  2, 1);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 500000,    NULL,     2, 1);
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      18000000, 3, 1);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 1400000,   NULL,     3, 1);
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      8700000,  1, 2);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 670000,    NULL,     1, 2);
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      6700000,  2, 2);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 520000,    NULL,     2, 2);
INSERT INTO REGLA_COBRO VALUES ('GLOBAL',   NULL,      18500000, 3, 2);
INSERT INTO REGLA_COBRO VALUES ('CREDITOS', 1450000,   NULL,     3, 2);

-- 0.12 PERSONA
INSERT INTO PERSONA VALUES (1001234567, 'Carlos',  'Mendoza', 'cmendoza@uni.edu.co', '3001234567');
INSERT INTO PERSONA VALUES (1002345678, 'Ana',     'Perez',   'aperez@uni.edu.co',   '3007654321');
INSERT INTO PERSONA VALUES (1003456789, 'Luis',    'Torres',  'ltorres@uni.edu.co',  '3009876543');

-- 0.13 USUARIO
INSERT INTO USUARIO (ID_USER, USERNAME, CONTRASENA, ID_PERFIL, CEDULA)
    SELECT SEQ_USUARIO.NEXTVAL, 'cmendoza', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', ID_PERFIL, 1001234567 FROM PERFIL WHERE NOMBRE_PERFIL = 'ADMINISTRADOR';
INSERT INTO USUARIO (ID_USER, USERNAME, CONTRASENA, ID_PERFIL, CEDULA)
    SELECT SEQ_USUARIO.NEXTVAL, 'aperez', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', ID_PERFIL, 1002345678 FROM PERFIL WHERE NOMBRE_PERFIL = 'SUPERVISOR';
INSERT INTO USUARIO (ID_USER, USERNAME, CONTRASENA, ID_PERFIL, CEDULA)
    SELECT SEQ_USUARIO.NEXTVAL, 'ltorres', 'ef92b778bafe771e89245b89ecbc08a44a4e166c06659911881f383d4473e94f', ID_PERFIL, 1003456789 FROM PERFIL WHERE NOMBRE_PERFIL = 'ASISTENTE';

-- 0.14 ESTUDIANTE
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-SIS-001', 'Maria',   'Garcia',  '3012345678', 'mgarcia@est.uni.edu.co',  1);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-SIS-002', 'Pedro',   'Lopez',   '3023456789', 'plopez@est.uni.edu.co',   1);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-ADM-001', 'Laura',   'Ramirez', '3034567890', 'lramirez@est.uni.edu.co', 2);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-MED-001', 'Andres',  'Herrera', '3045678901', 'aherrera@est.uni.edu.co', 3);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-MED-002', 'Juliana', 'Castro',  '3056789012', 'jcastro@est.uni.edu.co',  3);

COMMIT;
PROMPT >>> Datos base insertados.

-- ============================================================
-- SECCION 1: LIMPIEZA PREVIA (datos adicionales de re-ejecucion)
-- ============================================================

DELETE FROM TRANSACCION_PAGO;
DELETE FROM MOVIMIENTO;
DELETE FROM VOLANTE_MATRICULA_ASIGNATURA;
DELETE FROM VOLANTE_MATRICULA;
DELETE FROM CUENTA_CORRIENTE;

DELETE FROM ESTUDIANTE WHERE CARNET IN (
    '2026-SIS-003','2026-SIS-004','2026-SIS-005',
    '2026-ADM-002','2026-ADM-003'
);
DELETE FROM PLAN_ESTUDIO_ASIGNATURA WHERE SEMESTRE = 3;
DELETE FROM PLAN_ESTUDIO_ASIGNATURA WHERE SEMESTRE IN (1,2)
    AND ID_ASIGNATURA >= 11;
DELETE FROM PLAN_ESTUDIO WHERE SEMESTRE = 3;
DELETE FROM ASIGNATURA WHERE ID_ASIGNATURA >= 11;
DELETE FROM PLAN_ESTUDIO_ASIGNATURA
WHERE (SEMESTRE=1 AND ID_PROGRAMA=1 AND ID_ASIGNATURA NOT IN (1,2,3,5))
   OR (SEMESTRE=2 AND ID_PROGRAMA=1 AND ID_ASIGNATURA NOT IN (4,8))
   OR (SEMESTRE=1 AND ID_PROGRAMA=2 AND ID_ASIGNATURA NOT IN (6,7,8))
   OR (SEMESTRE=2 AND ID_PROGRAMA=2 AND ID_ASIGNATURA NOT IN (1,8))
   OR (SEMESTRE=1 AND ID_PROGRAMA=3 AND ID_ASIGNATURA NOT IN (9,10))
   OR (SEMESTRE=2 AND ID_PROGRAMA=3 AND ID_ASIGNATURA NOT IN (5,8));

COMMIT;
-- ============================================================
-- SECCION 2: ASIGNATURAS ADICIONALES
-- El DDL tiene 10 asignaturas (IDs 1-10).
-- Se agregan 15 mas (IDs 11-25) para poder completar
-- 5 asignaturas por semestre en todos los semestres.
-- ============================================================
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Estadistica',               3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Logica Matematica',         3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Introduccion a Ingenieria', 2);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Estructuras de Datos',      3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Redes de Computadores',     3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Ingenieria de Software',    3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Sistemas Operativos',       3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Administracion I',          3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Derecho Comercial',         3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Gestion Humana',            3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Finanzas I',                3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Marketing',                 3);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Quimica General',           4);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Fisiologia',                4);
INSERT INTO ASIGNATURA (ID_ASIGNATURA, NOMBRE, CANT_CREDITOS)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, 'Bioquimica',                4);

COMMIT;
-- ============================================================
-- SECCION 3: COMPLETAR PLAN_ESTUDIO_ASIGNATURA SEM 1 Y 2
-- El DDL dejo algunos semestres con menos de 5 asignaturas.
-- Se completan aqui sin tocar las que ya existen.
-- Estado actual del DDL:
--   Sistemas  sem 1: asigs 1,2,3,5       (4) => falta 1
--   Sistemas  sem 2: asigs 4,8           (2) => faltan 3
--   Admin     sem 1: asigs 6,7,8         (3) => faltan 2
--   Admin     sem 2: asigs 1,8           (2) => faltan 3
--   Medicina  sem 1: asigs 9,10          (2) => faltan 3
--   Medicina  sem 2: asigs 5,8           (2) => faltan 3
-- ============================================================
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 1, 12);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 1, 11);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 1, 14);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 1, 15);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 2, 18);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 2, 19);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 2, 20);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 2, 21);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 2, 22);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 3, 23);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 3, 24);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (1, 3, 25);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 3, 11);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 3, 23);
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (2, 3, 24);

COMMIT;
-- ============================================================
-- SECCION 4: SEMESTRE 3 - PLAN_ESTUDIO Y ASIGNATURAS
-- Se agrega el semestre 3 para los 3 programas con
-- 5 asignaturas cada uno, usando las nuevas asignaturas.
-- ============================================================
INSERT INTO PLAN_ESTUDIO VALUES (3, 1); -- Sistemas sem 3
INSERT INTO PLAN_ESTUDIO VALUES (3, 2); -- Admin sem 3
INSERT INTO PLAN_ESTUDIO VALUES (3, 3); -- Medicina sem 3
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 1, 13); -- Intro Ingenieria  2 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 1, 16); -- Ing Software      3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 1, 17); -- Sist Operativos   3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 1, 11); -- Estadistica       3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 1,  8); -- Ingles I          2 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 2, 20); -- Gestion Humana    3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 2, 21); -- Finanzas I        3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 2, 22); -- Marketing         3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 2, 11); -- Estadistica       3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 2,  8); -- Ingles I          2 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 3, 24); -- Fisiologia        4 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 3, 25); -- Bioquimica        4 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 3, 23); -- Quimica General   4 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 3, 11); -- Estadistica       3 cred
INSERT INTO PLAN_ESTUDIO_ASIGNATURA VALUES (3, 3,  8); -- Ingles I          2 cred
COMMIT;
-- ============================================================
-- SECCION 5: ESTUDIANTES ADICIONALES
-- El DDL ya tiene 5 estudiantes:
--   ID 1: Maria Garcia    - Sistemas  (ID_PROG=1)
--   ID 2: Pedro Lopez     - Sistemas  (ID_PROG=1)
--   ID 3: Laura Ramirez   - Admin     (ID_PROG=2)
--   ID 4: Andres Herrera  - Medicina  (ID_PROG=3)
--   ID 5: Juliana Castro  - Medicina  (ID_PROG=3)
-- Se agregan 5 mas para llegar a 10.
-- ============================================================
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-SIS-003', 'Sofia',   'Vargas',   '3067890123', 'svargas@est.uni.edu.co',  1);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-SIS-004', 'Camilo',  'Reyes',    '3078901234', 'creyes@est.uni.edu.co',   1);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-SIS-005', 'Daniela', 'Moreno',   '3089012345', 'dmoreno@est.uni.edu.co',  1);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-ADM-002', 'Nicolas', 'Jimenez',  '3090123456', 'njimenez@est.uni.edu.co', 2);
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO, TELEFONO, CORREO, ID_PROGRAMA)
    VALUES (SEQ_ESTUDIANTE.NEXTVAL, '2026-ADM-003', 'Valeria', 'Ospina',   '3001234560', 'vospina@est.uni.edu.co',  2);

COMMIT;
-- ============================================================
-- SECCION 6: VOLANTES DE MATRICULA
-- Un volante por estudiante, periodo 2026-10 (ID_PERIODO=1).
-- Los triggers se encargan de:
--   TR_CREAR_CUENTA_CORRIENTE => crea CUENTA_CORRIENTE
--   TR_CALCULAR_MONTO_VOLANTE => calcula MONTO_TOTAL
--
-- Distribucion de modalidades y semestres:
--   Sistemas sem 1 GLOBAL  : Maria (1), Sofia (6)
--   Sistemas sem 2 CREDITOS: Pedro (2), Camilo (7)
--   Sistemas sem 3 GLOBAL  : Daniela (8)
--   Admin    sem 1 GLOBAL  : Laura (3), Nicolas (9)
--   Admin    sem 2 CREDITOS: Valeria (10)
--   Medicina sem 1 GLOBAL  : Andres (4)
--   Medicina sem 2 CREDITOS: Juliana (5)
--
-- Montos calculados por trigger segun REGLA_COBRO:
--   Sistemas  GLOBAL   periodo 1 => 8.500.000
--   Sistemas  CREDITOS periodo 1 => 650.000/cred
--     sem 2: asigs 4+8+11+14+15 = 3+2+3+3+3 = 14 cred => 9.100.000
--   Admin     GLOBAL   periodo 1 => 6.500.000
--   Admin     CREDITOS periodo 1 => 500.000/cred
--     sem 2: asigs 1+8+20+21+22 = 3+2+3+3+3 = 14 cred => 7.000.000
--   Medicina  GLOBAL   periodo 1 => 18.000.000
--   Medicina  CREDITOS periodo 1 => 1.400.000/cred
--     sem 2: asigs 5+8+11+23+24 = 3+2+3+4+4 = 16 cred => 22.400.000
-- ============================================================
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 1, 'INDIVIDUAL', 1, 1, 'GLOBAL', 1);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 2, 'INDIVIDUAL', 2, 1, 'CREDITOS', 1);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 1, 'MASIVA', 3, 1, 'GLOBAL', 2);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 1, 'MASIVA', 4, 1, 'GLOBAL', 3);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 2, 'INDIVIDUAL', 5, 1, 'CREDITOS', 3);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 1, 'MASIVA', 6, 1, 'GLOBAL', 1);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 2, 'INDIVIDUAL', 7, 1, 'CREDITOS', 1);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 3, 'INDIVIDUAL', 8, 1, 'GLOBAL', 1);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 1, 'MASIVA', 9, 1, 'GLOBAL', 2);
INSERT INTO VOLANTE_MATRICULA
    (ID_VOLANTE, SEMESTRE_QUE_COBRA, TIPO_GENERACION, ID_ESTUDIANTE, ID_PERIODO, MODALIDAD, ID_PROGRAMA)
VALUES (SEQ_VOLANTE.NEXTVAL, 2, 'INDIVIDUAL', 10, 1, 'CREDITOS', 2);
COMMIT;

-- ============================================================
-- SECCION 7: VOLANTE_MATRICULA_ASIGNATURA
-- Solo para volantes con MODALIDAD = CREDITOS:
--   Volante 2  - Pedro   - Sistemas sem 2 - asigs 4,8,11,14,15
--   Volante 5  - Juliana - Medicina sem 2 - asigs 5,8,11,23,24
--   Volante 7  - Camilo  - Sistemas sem 2 - asigs 4,8,11,14,15
--   Volante 10 - Valeria - Admin    sem 2 - asigs 1,8,20,21,22
-- ============================================================
ALTER TRIGGER TR_RECALCULAR_MONTO_CREDITOS DISABLE;
-- Pedro Lopez (2026-SIS-002) - Sistemas sem 2 - CREDITOS
INSERT INTO VOLANTE_MATRICULA_ASIGNATURA (ID_ASIGNATURA, ID_VOLANTE)
    SELECT a.ID_ASIGNATURA, v.ID_VOLANTE
    FROM ASIGNATURA a
    JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = (
        SELECT ID_ESTUDIANTE FROM ESTUDIANTE WHERE CARNET = '2026-SIS-002')
    WHERE a.NOMBRE IN ('Bases de Datos I', 'Inglés I', 'Estadistica',
                       'Estructuras de Datos', 'Redes de Computadores');
-- Juliana Castro (2026-MED-002) - Medicina sem 2 - CREDITOS
INSERT INTO VOLANTE_MATRICULA_ASIGNATURA (ID_ASIGNATURA, ID_VOLANTE)
    SELECT a.ID_ASIGNATURA, v.ID_VOLANTE
    FROM ASIGNATURA a
    JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = (
        SELECT ID_ESTUDIANTE FROM ESTUDIANTE WHERE CARNET = '2026-MED-002')
    WHERE a.NOMBRE IN ('Física I', 'Inglés I', 'Estadistica',
                       'Quimica General', 'Fisiologia');
-- Camilo Reyes (2026-SIS-004) - Sistemas sem 2 - CREDITOS
INSERT INTO VOLANTE_MATRICULA_ASIGNATURA (ID_ASIGNATURA, ID_VOLANTE)
    SELECT a.ID_ASIGNATURA, v.ID_VOLANTE
    FROM ASIGNATURA a
    JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = (
        SELECT ID_ESTUDIANTE FROM ESTUDIANTE WHERE CARNET = '2026-SIS-004')
    WHERE a.NOMBRE IN ('Bases de Datos I', 'Inglés I', 'Estadistica',
                       'Estructuras de Datos', 'Redes de Computadores');
-- Valeria Ospina (2026-ADM-003) - Admin sem 2 - CREDITOS
INSERT INTO VOLANTE_MATRICULA_ASIGNATURA (ID_ASIGNATURA, ID_VOLANTE)
    SELECT a.ID_ASIGNATURA, v.ID_VOLANTE
    FROM ASIGNATURA a
    JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = (
        SELECT ID_ESTUDIANTE FROM ESTUDIANTE WHERE CARNET = '2026-ADM-003')
    WHERE a.NOMBRE IN ('Cálculo Diferencial', 'Inglés I', 'Gestion Humana',
                       'Finanzas I', 'Marketing');
COMMIT;
ALTER TRIGGER TR_RECALCULAR_MONTO_CREDITOS ENABLE;

-- ============================================================
-- SECCION 8: MOVIMIENTOS DE COBRO
-- Un cobro por volante usando el codigo correspondiente:
--   PMAT = cobro matricula GLOBAL
--   PCRE = cobro matricula CREDITOS
-- ID_CUENTA se obtiene desde CUENTA_CORRIENTE del estudiante.
-- ============================================================
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 8500000,
       'PMAT', cc.ID_CUENTA, 1, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 1;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'PCRE', cc.ID_CUENTA, 2, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 2
WHERE cc.ID_ESTUDIANTE = 2;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 6500000,
       'PMAT', cc.ID_CUENTA, 3, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 3;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 18000000,
       'PMAT', cc.ID_CUENTA, 4, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 4;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'PCRE', cc.ID_CUENTA, 5, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 5
WHERE cc.ID_ESTUDIANTE = 5;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 8500000,
       'PMAT', cc.ID_CUENTA, 6, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 6;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'PCRE', cc.ID_CUENTA, 7, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 7
WHERE cc.ID_ESTUDIANTE = 7;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 8500000,
       'PMAT', cc.ID_CUENTA, 8, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 8;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 6500000,
       'PMAT', cc.ID_CUENTA, 9, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 9;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'PCRE', cc.ID_CUENTA, 10, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 10
WHERE cc.ID_ESTUDIANTE = 10;
COMMIT;

-- ============================================================
-- SECCION 9: MOVIMIENTOS DE PAGO
-- Escenarios variados para demostrar los tres estados:
--   PAGADO    => pagos totales >= cobro total
--   PARCIAL   => 0 < pagos < cobro
--   PENDIENTE => sin ningun pago
--
-- Distribucion de estados:
--   PAGADO   : Maria(1), Pedro(2), Laura(3), Sofia(6), Camilo(7)
--   PARCIAL  : Andres(4), Daniela(8), Nicolas(9)
--   PENDIENTE: Juliana(5), Valeria(10)
-- ============================================================
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 8500000,
       'MPAG', cc.ID_CUENTA, 1, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 1;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'MPAG', cc.ID_CUENTA, 2, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 2
WHERE cc.ID_ESTUDIANTE = 2;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 4000000,
       'ANT', cc.ID_CUENTA, 3, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 3;

INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 2500000,
       'DESC', cc.ID_CUENTA, 3, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 3;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 8500000,
       'CRED', cc.ID_CUENTA, 6, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 6;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, v.MONTO_TOTAL,
       'MPAG', cc.ID_CUENTA, 7, 1
FROM CUENTA_CORRIENTE cc
JOIN VOLANTE_MATRICULA v ON v.ID_ESTUDIANTE = cc.ID_ESTUDIANTE AND v.ID_VOLANTE = 7
WHERE cc.ID_ESTUDIANTE = 7;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 10000000,
       'ANT', cc.ID_CUENTA, 4, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 4;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 3000000,
       'MPAG', cc.ID_CUENTA, 8, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 8;
INSERT INTO MOVIMIENTO (ID_MOV,FECHA,VALOR,CODIGO_DETALLE,ID_CUENTA,ID_VOLANTE,ID_PERIODO)
SELECT SEQ_MOVIMIENTO.NEXTVAL, SYSDATE, 1500000,
       'DESC', cc.ID_CUENTA, 9, 1
FROM CUENTA_CORRIENTE cc WHERE cc.ID_ESTUDIANTE = 9;
COMMIT;
-- ============================================================
-- SECCION 10: TRANSACCIONES DE PAGO
-- Solo para movimientos MPAG y ANT (dinero real).
-- DESC y CRED son ajustes contables, no generan transaccion.
-- ============================================================
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-001', 'EFECTIVO', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 1 AND m.CODIGO_DETALLE = 'MPAG';
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-002', 'TRANSFERENCIA', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 2 AND m.CODIGO_DETALLE = 'MPAG';
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-003', 'PSE', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 3 AND m.CODIGO_DETALLE = 'ANT';
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-004', 'EFECTIVO', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 4 AND m.CODIGO_DETALLE = 'ANT';
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-005', 'TARJETA', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 7 AND m.CODIGO_DETALLE = 'MPAG';
INSERT INTO TRANSACCION_PAGO (ID_TRANSACCION,REFERENCIA,MEDIO_PAGO,FECHA_PAGO,ID_MOV)
SELECT SEQ_TRANSACCION.NEXTVAL, 'REF-2026-006', 'PSE', SYSDATE, m.ID_MOV
FROM MOVIMIENTO m JOIN CUENTA_CORRIENTE cc ON cc.ID_CUENTA = m.ID_CUENTA
WHERE cc.ID_ESTUDIANTE = 8 AND m.CODIGO_DETALLE = 'MPAG';
COMMIT;

-- ============================================================
-- SECCION 11: VERIFICACION DE DATOS
-- ============================================================

PROMPT ============================================
PROMPT  1. RESUMEN GENERAL DE TABLAS
PROMPT ============================================
SELECT *
FROM (
    SELECT 'ASIGNATURA'                    AS TABLA, COUNT(*) AS FILAS FROM ASIGNATURA                    UNION ALL
    SELECT 'PLAN_ESTUDIO',                            COUNT(*)           FROM PLAN_ESTUDIO                UNION ALL
    SELECT 'PLAN_ESTUDIO_ASIGNATURA',                 COUNT(*)           FROM PLAN_ESTUDIO_ASIGNATURA     UNION ALL
    SELECT 'ESTUDIANTE',                              COUNT(*)           FROM ESTUDIANTE                  UNION ALL
    SELECT 'CUENTA_CORRIENTE',                        COUNT(*)           FROM CUENTA_CORRIENTE            UNION ALL
    SELECT 'VOLANTE_MATRICULA',                       COUNT(*)           FROM VOLANTE_MATRICULA           UNION ALL
    SELECT 'VOLANTE_MATRICULA_ASIGNATURA',            COUNT(*)           FROM VOLANTE_MATRICULA_ASIGNATURA UNION ALL
    SELECT 'MOVIMIENTO',                              COUNT(*)           FROM MOVIMIENTO                  UNION ALL
    SELECT 'TRANSACCION_PAGO',                        COUNT(*)           FROM TRANSACCION_PAGO
)
ORDER BY TABLA;

PROMPT ============================================
PROMPT  2. PLAN DE ESTUDIO - 5 ASIGNATURAS POR SEMESTRE
PROMPT ============================================
SELECT pe.SEMESTRE, pa.NOMBRE_PROGRAMA, COUNT(*) AS ASIGNATURAS
FROM PLAN_ESTUDIO_ASIGNATURA pe
JOIN PROGRAMA_ACADEMICO pa ON pa.ID_PROGRAMA = pe.ID_PROGRAMA
GROUP BY pe.SEMESTRE, pe.ID_PROGRAMA, pa.NOMBRE_PROGRAMA
ORDER BY pa.NOMBRE_PROGRAMA, pe.SEMESTRE;

PROMPT ============================================
PROMPT  3. VOLANTES POR ESTUDIANTE
PROMPT ============================================
SELECT
    v.ID_VOLANTE,
    e.CARNET,
    e.NOMBRE || ' ' || e.APELLIDO   AS ESTUDIANTE,
    pa.NOMBRE_PROGRAMA,
    v.SEMESTRE_QUE_COBRA            AS SEM,
    v.MODALIDAD,
    v.MONTO_TOTAL
FROM VOLANTE_MATRICULA   v
JOIN ESTUDIANTE          e  ON e.ID_ESTUDIANTE  = v.ID_ESTUDIANTE
JOIN PROGRAMA_ACADEMICO  pa ON pa.ID_PROGRAMA   = v.ID_PROGRAMA
ORDER BY v.ID_VOLANTE;

PROMPT ============================================
PROMPT  4. ESTADOS DE CUENTA (calculado desde movimientos)
PROMPT ============================================
SELECT
    sp.ESTUDIANTE,
    sp.NOMBRE_PERIODO,
    sp.TOTAL_COBROS,
    sp.TOTAL_PAGOS,
    sp.SALDO_NETO,
    CASE
        WHEN sp.SALDO_NETO <= 0                          THEN 'PAGADO'
        WHEN sp.TOTAL_PAGOS > 0 AND sp.SALDO_NETO > 0   THEN 'PARCIAL'
        ELSE                                                  'PENDIENTE'
    END AS ESTADO
FROM VW_SALDO_PERIODO sp
ORDER BY ESTADO, sp.ESTUDIANTE;

PROMPT ============================================
PROMPT  5. ASIGNATURAS POR VOLANTE CREDITOS
PROMPT ============================================
SELECT
    v.ID_VOLANTE,
    e.NOMBRE || ' ' || e.APELLIDO   AS ESTUDIANTE,
    a.NOMBRE                         AS ASIGNATURA,
    a.CANT_CREDITOS                  AS CREDITOS
FROM VOLANTE_MATRICULA_ASIGNATURA vma
JOIN VOLANTE_MATRICULA  v  ON v.ID_VOLANTE    = vma.ID_VOLANTE
JOIN ASIGNATURA         a  ON a.ID_ASIGNATURA = vma.ID_ASIGNATURA
JOIN ESTUDIANTE         e  ON e.ID_ESTUDIANTE = v.ID_ESTUDIANTE
ORDER BY v.ID_VOLANTE, a.CANT_CREDITOS DESC;

PROMPT ============================================
PROMPT  6. TODOS LOS MOVIMIENTOS
PROMPT ============================================
SELECT
    m.ID_MOV,
    e.NOMBRE || ' ' || e.APELLIDO   AS ESTUDIANTE,
    m.CODIGO_DETALLE,
    cd.GRUPO,
    m.VALOR
FROM MOVIMIENTO        m
JOIN CUENTA_CORRIENTE  cc ON cc.ID_CUENTA      = m.ID_CUENTA
JOIN ESTUDIANTE        e  ON e.ID_ESTUDIANTE   = cc.ID_ESTUDIANTE
JOIN CODIGO_DETALLE    cd ON cd.CODIGO_DETALLE = m.CODIGO_DETALLE
ORDER BY m.ID_MOV;

PROMPT ============================================
PROMPT  7. TRANSACCIONES DE PAGO
PROMPT ============================================
SELECT
    tp.ID_TRANSACCION,
    tp.REFERENCIA,
    tp.MEDIO_PAGO,
    m.VALOR                          AS VALOR_PAGADO,
    e.NOMBRE || ' ' || e.APELLIDO   AS ESTUDIANTE
FROM TRANSACCION_PAGO  tp
JOIN MOVIMIENTO        m  ON m.ID_MOV        = tp.ID_MOV
JOIN CUENTA_CORRIENTE  cc ON cc.ID_CUENTA    = m.ID_CUENTA
JOIN ESTUDIANTE        e  ON e.ID_ESTUDIANTE = cc.ID_ESTUDIANTE
ORDER BY tp.ID_TRANSACCION;


PROMPT ============================================
PROMPT  8. VW_SALDO_PERIODO - BALANCE POR ESTUDIANTE
PROMPT ============================================
SELECT
    ESTUDIANTE,
    NOMBRE_PERIODO,
    TOTAL_COBROS,
    TOTAL_PAGOS,
    SALDO_NETO
FROM VW_SALDO_PERIODO
ORDER BY SALDO_NETO, ESTUDIANTE;

PROMPT ============================================
PROMPT  9. VW_PENDIENTES_PAGO
PROMPT ============================================
SELECT
    NOMBRE_ESTUDIANTE || ' ' || APELLIDO_ESTUDIANTE  AS ESTUDIANTE,
    NOMBRE_PROGRAMA,
    TOTAL_COBRADO,
    TOTAL_PAGADO,
    SALDO_PENDIENTE,
    ESTADO
FROM VW_PENDIENTES_PAGO
ORDER BY ESTADO, NOMBRE_ESTUDIANTE;

PROMPT ============================================
PROMPT  10. VW_INGRESO_ESPERADO
PROMPT ============================================
SELECT
    NOMBRE_PERIODO,
    NOMBRE_PROGRAMA,
    TOTAL_ESPERADO
FROM VW_INGRESO_ESPERADO
ORDER BY NOMBRE_PROGRAMA;

PROMPT ============================================
PROMPT  11. VW_INGRESO_REAL
PROMPT ============================================
SELECT
    NOMBRE_PERIODO,
    TOTAL_RECAUDADO
FROM VW_INGRESO_REAL
ORDER BY NOMBRE_PERIODO;

PROMPT ============================================
PROMPT  12. MALLA ACADEMICA - MATERIAS POR SEMESTRE Y CARRERA
PROMPT ============================================
SELECT
    pa.NOMBRE_PROGRAMA                          AS PROGRAMA,
    pea.SEMESTRE,
    a.NOMBRE                                    AS ASIGNATURA,
    a.CANT_CREDITOS                             AS CREDITOS
FROM PLAN_ESTUDIO_ASIGNATURA pea
JOIN PROGRAMA_ACADEMICO pa ON pa.ID_PROGRAMA   = pea.ID_PROGRAMA
JOIN ASIGNATURA         a  ON a.ID_ASIGNATURA  = pea.ID_ASIGNATURA
ORDER BY pa.NOMBRE_PROGRAMA, pea.SEMESTRE, a.NOMBRE;